/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
  License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
  Source: https://sketchfab.com/3d-models/fox-f372c04de44640fbb6a4f9e4e5845c78
  Title: Fox
*/

// Import React hooks and components
import { useEffect, useMemo, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import type { ThreeElements } from "@react-three/fiber";
import { clone } from "three/addons/utils/SkeletonUtils.js";
import type { Bone, Group, MeshStandardMaterial, SkinnedMesh } from "three";
import type { GLTF } from "three/addons/loaders/GLTFLoader.js";

// Import the 3D model file for the fox
import foxScene from "../assets/3d/fox.glb";

export type FoxAnimation = "idle" | "walk" | "hit";

type FoxProps = ThreeElements["group"] & {
  currentAnimation: FoxAnimation;
};

type GLTFResult = GLTF & {
  nodes: {
    GLTF_created_0_rootJoint: Bone;
    Object_7: SkinnedMesh;
    Object_8: SkinnedMesh;
    Object_9: SkinnedMesh;
    Object_10: SkinnedMesh;
    Object_11: SkinnedMesh;
  };
  materials: {
    PaletteMaterial001: MeshStandardMaterial;
  };
};

// Fox component definition
const Fox = ({ currentAnimation, ...props }: FoxProps) => {
  // Create a reference for the group that contains the fox model
  const group = useRef<Group>(null);

  // Load the 3D model and animations using useGLTF and useAnimations hooks
  const { scene, animations } = useGLTF(foxScene);
  const clonedScene = useMemo(() => clone(scene), [scene]);
  const { nodes, materials } = useGraph(clonedScene) as unknown as Pick<
    GLTFResult,
    "nodes" | "materials"
  >;
  const { actions } = useAnimations(animations, group);

  // Use useEffect to play the specified animation when it changes
  useEffect(() => {
    // Stop all existing animations
    Object.values(actions).forEach((action) => action?.stop());

    // Play the selected animation if it exists
    actions[currentAnimation]?.play();
  }, [actions, currentAnimation]);

  // Return the JSX for the Fox component with group, mesh, and skeleton
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />

        {/* SkinnedMesh components for different parts of the fox */}
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_8.skeleton}
        />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_9.skeleton}
        />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_10.skeleton}
        />
        <skinnedMesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_11.skeleton}
        />
      </group>
    </group>
  );
};

// Export the Fox component as the default export
export default Fox;
