/* eslint-disable react/no-unknown-property */
/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
  Author: nimzu (https://sketchfab.com/nimzuk)
  License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
  Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
  Title: Fox's islands
*/

// Import React hooks and components
import { useRef, useEffect, useCallback } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

// Import the 3D model file for the island
import islandScene from "../assets/3d/island.glb";

// Island component definition
const Island = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
  // Create a reference for the island group
  const islandRef = useRef();

  // Destructure values from useThree hook for camera and viewport information
  const { gl, viewport } = useThree();

  // Load the 3D model using useGLTF hook
  const { nodes, materials } = useGLTF(islandScene);

  // Create refs for tracking last X position, rotation speed, and initial rotation
  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  // Event handlers for pointer and keyboard input
  const handlePointerDown = useCallback(
    (e) => {
      e.stopPropagation();
      e.preventDefault();
      setIsRotating(true);

      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      lastX.current = clientX;
    },
    [setIsRotating]
  );

  const handlePointerUp = useCallback(
    (e) => {
      e.stopPropagation();
      e.preventDefault();
      setIsRotating(false);
    },
    [setIsRotating]
  );

  const handlePointerMove = useCallback(
    (e) => {
      e.stopPropagation();
      e.preventDefault();

      if (isRotating) {
        const clientX = e.touches ? e.touches[0].clientX : e.clientX;
        const delta = (clientX - lastX.current) / viewport.width;

        // Rotate the island based on pointer movement
        islandRef.current.rotation.y += delta * 0.01 * Math.PI;
        lastX.current = clientX;
        rotationSpeed.current = delta * 0.01 * Math.PI;
      }
    },
    [viewport.width, isRotating]
  );

  const handleKeyDown = useCallback(
    (e) => {
      // Rotate the island based on arrow key press
      if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
        if (!isRotating) setIsRotating(true);
        islandRef.current.rotation.y +=
          (e.key === "ArrowLeft" ? 1 : -1) * 0.01 * Math.PI;
        rotationSpeed.current = (e.key === "ArrowLeft" ? 1 : -1) * 0.0125;
      }
    },
    [isRotating, setIsRotating]
  );

  const handleKeyUp = useCallback(
    (e) => {
      // Stop rotating when arrow key is released
      if (e.key === "ArrowLeft" || e.key === "ArrowRight") setIsRotating(false);
    },
    [setIsRotating]
  );

  // Use useFrame hook for animation logic
  useFrame(() => {
    if (!isRotating) {
      // Damping effect when not rotating
      rotationSpeed.current *= dampingFactor;

      // Stop rotation when speed is very low
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      // Rotate the island based on the current rotation speed
      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = islandRef.current.rotation.y;

      // Normalize rotation to be between 0 and 2*pi
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }
  });

  // Use useEffect for adding and removing event listeners
  useEffect(() => {
    const canvas = gl.domElement;

    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("keyup", handleKeyUp);

    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("keyup", handleKeyUp);
    };
  }, [
    gl,
    handlePointerDown,
    handlePointerUp,
    handlePointerMove,
    handleKeyDown,
    handleKeyUp,
  ]);

  // Return the JSX for the Island component with group and mesh elements
  return (
    <a.group ref={islandRef} {...props}>
      <mesh
        geometry={nodes.polySurface944_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface945_tree1_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface946_tree2_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface947_tree1_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface948_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.polySurface949_tree_body_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.pCube11_rocks1_0.geometry}
        material={materials.PaletteMaterial001}
      />
    </a.group>
  );
};

// Export the Island component as the default export
export default Island;
